[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_chat = "7PTHeLBQNpZTr72sTWHcL1ZLpcrhcnLf2rSqmEN2pGWG"

# [programs.devnet]
# solana_chat = "7PTHeLBQNpZTr72sTWHcL1ZLpcrhcnLf2rSqmEN2pGWG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
# cluster = "devnet"
wallet = "/home/kevin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
